setwd("C:\\Users\\arun\\Desktop\\DATA SCIENCE FOLDER\\Simple Linear Regression\\Question4")
salary_data = read.csv("Salary_Data.csv")
View(salary_data)
mean(salary_data$YearsExperience)
median(salary_data$YearsExperience)
sd(salary_data$YearsExperience)
skewness(salary_data$YearsExperience)
kurtosis(salary_data$YearsExperience)
boxplot(salary_data$YearsExperience)
hist(salary_data$YearsExperience)
qqnorm(salary_data$YearsExperience)
qqline(salary_data$YearsExperience)
shapiro.test(salary_data$YearsExperience)
plot(salary_data$YearsExperience,salary_data$Salary)
cor(salary_data$YearsExperience,salary_data$Salary)
cor(salary_data$Salary,salary_data$YearsExperience)
salary_model = lm(salary_data$Salary~salary_data$YearsExperience)
summary(salary_model)
confint(salary_model, level = 0.95)
